"""'questions'

Revision ID: 3d8514d11619
Revises: 3c96ca16230f
Create Date: 2020-04-25 22:16:14.475955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8514d11619'
down_revision = '3c96ca16230f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=140), nullable=True),
    sa.Column('answers', sa.String(length=140), nullable=True),
    sa.Column('correct_answer', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_question'), 'questions', ['question'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_question'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
